### ISSUE TITLE
360 Images Conflict with Youtube Product Videos in PDP Gallery

### ISSUE THREAD

**Issue by ajithkumar-maragathavel** [webrotate360/magento2-standard#2] opened 2020-08-08 05:37 UTC
## Prerequisite

1. Magento 2.3.5 vanilla installation.
2. Install WebRotate360 extension and configure it.
3. Create a product and configure the sample 360 Image for that particular product.
4. Configure youtube video for that particular product.
5. Keep the gallery thumbnail sort order like Step-6.
6. 360 Image thumbnail, Youtube Video

## Steps to Reproduce

1. Goto the Product detail page of that particular product.
2. 360 Image is loaded by default and verify it is working fine.
3. Click the product video thumbnail to switch to the video on the product gallery.
4. Now click again on the 360 Image thumbnail
5. Verify the 360 images is not working and It is overlapped with the product video.

## Note

This issue only occurs when you keep the Gallery thumbnail sort order like 360 Images, Youtube videos.
Please let me know If you have any quick fix for this issue.

**Comment by webrotate360** [comment] 2020-09-06 20:42
Thanks for the feedback! We're investigating.

**Comment by webrotate360** [comment] 2020-11-13 01:07
The issue is resolved in the last commit.

**Closed as completed by webrotate360** 2020-11-13 01:07 UTC
